// all exports here for better tree shaking compat

export { amber as amberDark } from "./src/dark/amber";
export { blue as blueDark } from "./src/dark/blue";
export { bronze as bronzeDark } from "./src/dark/bronze";
export { brown as brownDark } from "./src/dark/brown";
export { crimson as crimsonDark } from "./src/dark/crimson";
export { cyan as cyanDark } from "./src/dark/cyan";
export { gold as goldDark } from "./src/dark/gold";
export { grass as grassDark } from "./src/dark/grass";
export { gray as grayDark } from "./src/dark/gray";
export { green as greenDark } from "./src/dark/green";
export { indigo as indigoDark } from "./src/dark/indigo";
export { lime as limeDark } from "./src/dark/lime";
export { mint as mintDark } from "./src/dark/mint";
export { olive as oliveDark } from "./src/dark/olive";
export { orange as orangeDark } from "./src/dark/orange";
export { pink as pinkDark } from "./src/dark/pink";
export { plum as plumDark } from "./src/dark/plum";
export { purple as purpleDark } from "./src/dark/purple";
export { mauve as mauveDark } from "./src/dark/mauve";
export { red as redDark } from "./src/dark/red";
export { sage as sageDark } from "./src/dark/sage";
export { sand as sandDark } from "./src/dark/sand";
export { sky as skyDark } from "./src/dark/sky";
export { slate as slateDark } from "./src/dark/slate";
export { teal as tealDark } from "./src/dark/teal";
export { tomato as tomatoDark } from "./src/dark/tomato";
export { violet as violetDark } from "./src/dark/violet";
export { yellow as yellowDark } from "./src/dark/yellow";

export { amberA as amberDarkA } from "./src/dark/amberA";
export { blueA as blueDarkA } from "./src/dark/blueA";
export { bronzeA as bronzeDarkA } from "./src/dark/bronzeA";
export { brownA as brownDarkA } from "./src/dark/brownA";
export { crimsonA as crimsonDarkA } from "./src/dark/crimsonA";
export { cyanA as cyanDarkA } from "./src/dark/cyanA";
export { goldA as goldDarkA } from "./src/dark/goldA";
export { grassA as grassDarkA } from "./src/dark/grassA";
export { grayA as grayDarkA } from "./src/dark/grayA";
export { greenA as greenDarkA } from "./src/dark/greenA";
export { indigoA as indigoDarkA } from "./src/dark/indigoA";
export { limeA as limeDarkA } from "./src/dark/limeA";
export { mintA as mintDarkA } from "./src/dark/mintA";
export { oliveA as oliveDarkA } from "./src/dark/oliveA";
export { orangeA as orangeDarkA } from "./src/dark/orangeA";
export { pinkA as pinkDarkA } from "./src/dark/pinkA";
export { plumA as plumDarkA } from "./src/dark/plumA";
export { purpleA as purpleDarkA } from "./src/dark/purpleA";
export { mauveA as mauveDarkA } from "./src/dark/mauveA";
export { redA as redDarkA } from "./src/dark/redA";
export { sageA as sageDarkA } from "./src/dark/sageA";
export { sandA as sandDarkA } from "./src/dark/sandA";
export { skyA as skyDarkA } from "./src/dark/skyA";
export { slateA as slateDarkA } from "./src/dark/slateA";
export { tealA as tealDarkA } from "./src/dark/tealA";
export { tomatoA as tomatoDarkA } from "./src/dark/tomatoA";
export { violetA as violetDarkA } from "./src/dark/violetA";
export { yellowA as yellowDarkA } from "./src/dark/yellowA";

export { amber } from "./src/light/amber";
export { blue } from "./src/light/blue";
export { bronze } from "./src/light/bronze";
export { brown } from "./src/light/brown";
export { crimson } from "./src/light/crimson";
export { cyan } from "./src/light/cyan";
export { gold } from "./src/light/gold";
export { grass } from "./src/light/grass";
export { gray } from "./src/light/gray";
export { green } from "./src/light/green";
export { indigo } from "./src/light/indigo";
export { lime } from "./src/light/lime";
export { mint } from "./src/light/mint";
export { olive } from "./src/light/olive";
export { orange } from "./src/light/orange";
export { pink } from "./src/light/pink";
export { plum } from "./src/light/plum";
export { purple } from "./src/light/purple";
export { mauve } from "./src/light/mauve";
export { red } from "./src/light/red";
export { sage } from "./src/light/sage";
export { sand } from "./src/light/sand";
export { sky } from "./src/light/sky";
export { slate } from "./src/light/slate";
export { teal } from "./src/light/teal";
export { tomato } from "./src/light/tomato";
export { violet } from "./src/light/violet";
export { yellow } from "./src/light/yellow";

export { amberA } from "./src/light/amberA";
export { blueA } from "./src/light/blueA";
export { bronzeA } from "./src/light/bronzeA";
export { brownA } from "./src/light/brownA";
export { crimsonA } from "./src/light/crimsonA";
export { cyanA } from "./src/light/cyanA";
export { goldA } from "./src/light/goldA";
export { grassA } from "./src/light/grassA";
export { grayA } from "./src/light/grayA";
export { greenA } from "./src/light/greenA";
export { indigoA } from "./src/light/indigoA";
export { limeA } from "./src/light/limeA";
export { mintA } from "./src/light/mintA";
export { oliveA } from "./src/light/oliveA";
export { orangeA } from "./src/light/orangeA";
export { pinkA } from "./src/light/pinkA";
export { plumA } from "./src/light/plumA";
export { purpleA } from "./src/light/purpleA";
export { mauveA } from "./src/light/mauveA";
export { redA } from "./src/light/redA";
export { sageA } from "./src/light/sageA";
export { sandA } from "./src/light/sandA";
export { skyA } from "./src/light/skyA";
export { slateA } from "./src/light/slateA";
export { tealA } from "./src/light/tealA";
export { tomatoA } from "./src/light/tomatoA";
export { violetA } from "./src/light/violetA";
export { yellowA } from "./src/light/yellowA";

export { blackA } from "./src/blackA";
export { whiteA } from "./src/whiteA";
